[tools]
swiftlint = "0.63.2"
tuist = "4.115.1"
periphery = "3.7.4"
pre-commit = "4.6.0"
node = "lts"

[tasks.bump-tools]
description = "Bump all tool versions to the latest"
run = "mise upgrade --bump && uv run pre-commit autoupdate && pnpm update --recursive"
